### ISSUE TITLE
Scoring quickly causes time to be incorrectly calculated for other players.

### ISSUE THREAD

**Issue by gortok** [thomasboyt/manygolf#1]
Game starts with 40 seconds.
Player A scores in 6.00 seconds.
Instead of being at 34 seconds, game is now at 10 seconds.
Player be scores in 9.00 seconds; game clock is at 7 seconds.

The game calculates player B's time as 33 seconds (40-7), instead of 9 seconds (the actual seconds that transpired between first shot and scoring).

The game should calculate time based on time between first shot and score; not based on the gameclock (since it gets reduced to 10 seconds as soon as the first person scores). I'd be happy to submit this change if you let me know where; I dont' quite follow where it's supposed to happen.

**Comment by neuhaus** [comment]
Did you deploy this on the server? It still shows the wrong time for the last player to finish.

**Comment by thomasboyt** [comment]
@neuhaus ah, you're right, looks like the deploy with this fix failed for some reason. Fixing now :)
