### ISSUE TITLE
Unavailable website (at least using Firefox) due to insecure certificate

### ISSUE THREAD

**Issue by pintassilgo** [thomasboyt/manygolf#26]
Trying to load https://manygolf.club/ using Firefox:
> Secure Connection Failed
> An error occurred during a connection to manygolf.club. Peer’s Certificate has been revoked.
> Error code: SEC_ERROR_REVOKED_CERTIFICATE
>    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>    Please contact the website owners to inform them of this problem.

This started today, until yesterday it was working.

You can see here that the certificate is insecure:
https://www.ssllabs.com/ssltest/analyze.html?d=manygolf.club&latest

![image](https://user-images.githubusercontent.com/5483864/152541682-23dc6c25-3730-4289-a7d9-16a13d3aad12.png)

**Comment by csteelatgburg** [comment]
I have been very bummed about this. Just commenting to share the misery.

**Comment by pintassilgo** [comment]
This was finally fixed today.
