### ISSUE TITLE
The node API for `babel` has been moved to `babel-core`

### ISSUE THREAD

**Issue by neuhaus** [thomasboyt/manygolf#9]
I'm trying to the the server locally but run into an error:

$ npm run server-watch

> manygolf@0.0.1 server-watch /tmp/git/manygolf
> scripts/server-watch

Hash: 3826e348d4504764c861
Version: webpack 1.13.1
Time: 435ms

ERROR in The node API for `babel` has been moved to `babel-core`.
module.js:442
    throw err;
    ^

Error: Cannot find module '/tmp/git/manygolf/build/server.bundle.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

I am using node 6.2, npm 3.8.9 and babel 6.5.2

What do I need to change to make manygolf use the newer `babel-core` instead of `babel`?
Merely changing the loader in the module module.exports in `webpack/server.js` from "babel" to "babel-core" doesn't suffice.

**Comment by thomasboyt** [comment]
hmm, I can't reproduce this. I'm running node 4.x and not node 6.x, but I don't think that should affect things. try reinstalling your dependencies? (in the repo root: `rm -rf node_modules/ && npm cache clean && npm install`)
